apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auditlogger.fullname" . }}
  labels:
    {{- include "auditlogger.labels" . | nindent 4 }}
type: Opaque
data:
  postgresConnectionString: {{ .Values.postgresConnectionString | b64enc }}
  
